excluded:
  - Pods
  - widget

opt_in_rules:
  - empty_count
  - empty_string

disabled_rules:
  - trailing_whitespace
  - trailing_comma     # managed by SwiftFormat
  - opening_brace      # conflicts with SwiftFormat's multiline brace style


type_name:
  allowed_symbols:
    - _

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  warning: 150
  error: 250

type_body_length:
  warning: 250
  error: 350
